homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 30.0016
  longitude: -95.4475
  elevation: 33
  # imperial for Imperial, metric for Metric
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago


  customize: 
    sensor.pws_weather: 
      friendly_name: 'Weather' 
      icon: mdi:cup-water
    sensor.pws_precip_today_in: 
      friendly_name: 'Preciptation Today' 
      icon: mdi:weather-rainy
    sensor.pws_relative_humidity: 
      friendly_name: 'Outdoor Humidity' 
      icon: mdi:water-percent
    sensor.pws_temp_f: 
      friendly_name: 'Outdoor Temp'
    sensor.pws_feelslike_f: 
      friendly_name: 'Feels Like Temp'
    sensor.pws_wind_mph:
      friendly_name: 'Wind Speed'
      icon: mdi:weather-windy
    sensor.pws_alerts:
      friendly_name: 'Weather Alerts'
    sensor.speedtest_download: 
      friendly_name: 'Download' 
      icon: mdi:speedometer 
    sensor.speedtest_upload: 
      friendly_name: 'Upload' 
      icon: mdi:speedometer
    sensor.speedtest_ping:
      friendly_name: 'Ping'
      icon: mdi:clock-fast
    sensor.back_doorsensor:
      friendly_name: 'Back Door Motion Sensor'
      icon: mdi:walk
    switch.master_bedroom_table_lamp:
      icon: mdi:lightbulb
    switch.den_table_lamp_stairs:
      icon: mdi:lightbulb
    switch.den_table_lamp_tv:
      icon: mdi:lightbulb
    switch.front_door_xmas_spot_light:
      friendly_name: 'Front Door Xmas Spotlight'
      icon: mdi:spotlight-beam
    switch.back_yard_lights:
      icon: mdi:spotlight-beam
    sensor.home_to_work:
      icon: mdi:car
    sensor.work_to_home:
      icon: mdi:car
    light.fireplace_xmas_lights:
      icon: mdi:led-on
    switch.christmas_tree__top:
      icon: mdi:pine-tree
    switch.christmas_tree__bot:
      icon: mdi:pine-tree
#   sensor.home_to_work: 
#     friendly_name: 'Home-Work' 
#     icon: mdi:car
 
      
## COMPONENTS ##
# Enables the frontend
frontend:
# Discover some devices automatically
discovery:
# Track the sun
sun:
# Show links to resources in log and frontend
# introduction:
# Allows you to issue voice commands from the frontend
# conversation:
# Checks for available updates
updater:
# View all events in a logbook
logbook:
# Enables support for tracking state changes over time.
history:
# Enables support for tracking state changes over time
recorder:
  purge_days: 14
    

## DEVICES ##
isy994:
  host: http://172.28.254.10:80
  username: admin
  password: admin
#  tls: 1.2
#  scan_interval: 3
    
switch pi:
  platform: rpi_gpio
  ports:
    18: LED Pi
    
    
## SENSORS ##
sensor:
# Prediction of weather
  - platform: wunderground
    api_key: xxxx
    monitored_conditions:
      - weather
      - temp_f
      - feelslike_f
      - wind_mph
      - relative_humidity
      - precip_today_in
#      - alerts

  - platform: speedtest 
    minute:
      - 0
      - 30    
    monitored_conditions:
      - ping 
      - download 
      - upload 

  - platform: google_travel_time
    name: Home to Work
    api_key: xxxx
    origin: 16407 Fox Crossing, Spring, Texas, 77379
    destination: Three Riverway, Houston, Texas, 77056
# can be ["driving", "walking", "bicycling", "transit"]
#    travel_mode: driving 

  - platform: google_travel_time
    name: Work to Home
    api_key: xxxx
    origin: Three Riverway, Houston, Texas, 77056
    destination: 16407 Fox Crossing, Spring, Texas, 77379

  - platform: yahoo_finance
    name: Hi-Crush
    symbol: HCLP

  - platform: yahoo_finance
    name: Fairmount
    symbol: FMSA

  - platform: yahoo_finance
    name: US Silica
    symbol: SLCA

  - platform: yahoo_finance
    name: Crude Oil
    symbol: CL=F
    
  - platform: template
    sensors:
      Backyard_light_timer:
        value_template: '{{(as_timestamp(now() - as_timestamp(switch.back_yard_lights.on) => 600}}'      

    
## AUTOMATION ##
automation:
  - alias: 'Update Notification'
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.notify
      data:
        message: 'There is a new Home Assistant release available...'
  - alias: 'HA Start'
    trigger:
      platform: event
      event_type: homeassistant_start
    action:
      service: notify.notify
      data:
        message: 'HA started'      
  - alias: 'HA Stop'
    trigger:
      platform: event
      event_type: homeassistant_stop
    action:
      service: notify.notify
      data:
        message: 'HA stopped'      

  
## NOTIFICATION ##
# notify:
#   - name: updater
#     platform: smtp
#     server: xxxx
   ## port: 587
#     sender: xxxx
    ## starttls: true
    ## username: xxx@gmail.com
    ## password: xxxx
#     recipient: xxxx
    
# Example SendGrid entry
notify:
  name: notify
  platform: sendgrid
  api_key: xxxx
  sender: xxxx
  recipient: xxxx


## GROUPS ##
group:
#  default_view:
  _Home Home:   
    name: Default
    icon: mdi:home
    view: yes
    entities:
      - updater.updater
      - group.current_weather
      - group.outside
      - group.den
      - group.master_bedroom
      - group.stocks
  Current Weather:
    - sensor.pws_weather
    - sensor.pws_temp_f
    - sensor.pws_relative_humidity
    - sensor.pws_feelslike_f
    - sensor.pws_wind_mph
    - sensor.pws_precip_today_in
    - sensor.pws_alerts
    - sun.sun
  Outside: 
    - sensor.back_doorsensor
    - switch.front_door_light
    - switch.back_door_lights
    - switch.back_yard_lights 
    - switch.garage_light
    - switch.outside_lights
  Master Bedroom:
    - switch.master_bedroom_table_lamp
  Den:
    - switch.den_table_lamp_tv
    - switch.den_table_lamp_stairs
  Internet:
    - sensor.speedtest_ping 
    - sensor.speedtest_download 
    - sensor.speedtest_upload 
  Traffic:
    - sensor.home_to_work 
    - sensor.work_to_home 
  Stocks:
    - sensor.hicrush
    - sensor.fairmount
    - sensor.us_silica
    - sensor.crude_oil
  Automation Group:
    - automation.ha_start
    - automation.update_notification
    
  Internet Stats:
    name: Internet
    view: yes  
    entities:    
      - group.internet
  Traffic Info:
    name: Traffic
    view: yes  
    entities:    
      - group.traffic
  Christmas Lights:
    name: Christmas
#    icon: mdi:pine-tree
    view: yes
    entities:
      - switch.christmas_lights_inside
      - switch.christmas_lights_outside
      - light.fireplace_xmas_lights
      - switch.christmas_tree__top
      - switch.christmas_tree__bot
      - switch.front_door_xmas_spot_light
  Stock Info:
    name: Stocks
    view: yes  
    entities:    
      - group.stocks
  Automation:
    name: Automation
    view: yes
    entities:
      - group.automation_group


#  •platform: mqtt
# state_topic: "thermostat"
# name: "Thermostat Operating Mode"
# value_template: "{{ value_json.tmode}"

# The expected values, and the corresponding strings I am interested are:
# 0: OFF
# 1: HEAT
# 2: COOL
# 3: AUTO 
# value_template: "{% if value_json.tmode == '0' %}OFF{% elif value_json.tmode == '1' %}HEAT{% elif value_json.tmode =='2' %}COOL{% elif value_json.tmode =='3' %}AUTO{% endif %}"